version: '3'
services:
  app:
    build: .
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=development
    command: pm2-runtime start ecosystem.config.js
  
  db:
    image: postgres:12
    ports:
      - "54323:5432"
    volumes:
      - ./initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
      - PostgresDBData:/POSTGRES
    environment:
      POSTGRES_DB: "vaccine_management"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"

volumes:
  PostgresDBData:
