name: 'coverage'
on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              id: coverage
              with:
                  test-script: yarn test --coverage
                  output: comment, report-markdown
                  annotations: coverage
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: ${{ steps.coverage.outputs.report }}